name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Clone repository
      - uses: actions/checkout@v3

      - name: install required modules
        uses: actions/setup-node@v3
        with:
          node-version: 16.17.1
  
      - run: npm install
      - name: run test
        env:
          NODE_ENV: ${{ secrets.NODE_ENV}}
          MONGODB_USER: ${{ secrets.MONGODB_USER }}
          MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
          MONGODB_DATABASE: ${{ secrets.MONGODB_DATABASE }}
          MONGODB_CONNECT_STRING: ${{ secrets.MONGODB_CONNECT_STRING }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          NEWEBPAY_HASHKEY: ${{ secrets.NEWEBPAY_HASHKEY }}
          NEWEBPAY_HASHIV: ${{ secrets.NEWEBPAY_HASHIV }}
          NEWEBPAY_MERCHANTID: ${{ secrets.NEWEBPAY_MERCHANTID }}
          NEWEBPAY_VERSION: ${{ secrets.NEWEBPAY_VERSION }}
          NEWEBPAY_REDIRECT: ${{ secrets.NEWEBPAY_REDIRECT }}
        run: npm run test