name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Clone repository
      - uses: actions/checkout@v3

      - name: install required modules
        uses: actions/setup-node@v3
        with:
          node-version: 16.17.1
  
      - run: npm install
      - run: npm run test 